apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: messaging
  namespace: argocd
spec:
  description: Skybridge real-time messaging platform (WorkshopPlus)
  sourceRepos:
    - https://github.com/REPLACE/aks-briefing-with-labs.git
  destinations:
    - namespace: 'messaging-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
