apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - api-node.yaml
  - web-react.yaml
  - worker-python.yaml
  - istio-routing.yaml
commonLabels:
  app.kubernetes.io/part-of: storefront
