# Dev ring — small replicas, latest images, no traffic gates.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messaging-dev
resources:
  - ../../base
patches:
  - target: { kind: Namespace, name: messaging }
    patch: |
      - op: replace
        path: /metadata/name
        value: messaging-dev
  - target: { kind: StatefulSet, name: gateway-java }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target: { kind: Deployment, name: parser-cpp }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: Deployment, name: ops-console }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
images:
  - name: REPLACE_ACR/gateway-java
    newTag: dev-latest
  - name: REPLACE_ACR/parser-cpp
    newTag: dev-latest
  - name: REPLACE_ACR/ops-console
    newTag: dev-latest
